.PHONY: clean All

All:
	@echo "----------Building project:[ ejercicioG2 - Debug ]----------"
	@cd "ejercicioG2" && "$(MAKE)" -f  "ejercicioG2.mk"
clean:
	@echo "----------Cleaning project:[ ejercicioG2 - Debug ]----------"
	@cd "ejercicioG2" && "$(MAKE)" -f  "ejercicioG2.mk" clean
